print("1. Hello, World!")
print("2. Python is fun!")
print("3. Let's learn to code.")
print("4. Keep practicing.")
print("5. Coding is creative.")
print("6. Debugging is important.")
print("7. Stay curious.")
print("8. Experiment with code.")
print("9. Never stop learning.")
print("10. Small steps lead to big results.")
print("11. Consistency is key.")
print("12. Automate repetitive tasks.")
print("13. Readability matters.")
print("14. Write clean code.")
print("15. Enjoy the process.")
print("16. Learn from mistakes.")
print("17. Challenge yourself.")
print("18. Explore new ideas.")
print("19. Break big problems into small ones.")
print("20. Happy coding!")
